### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by P0keDev** [swindlesmccoop/bad-apple-arduino#1]
It's nice to see someone get use out of midi2arduino, haha

Apologies for the obtuse nature of the project - I'm glad you figured things out regardless

**Comment by swindlesmccoop** [comment]
Thanks for making the project in the first place. I saw people hooking up SD cards and speakers and playing it, but that looked lame to me. I'm curious on how you even found this, though, the video has less than 100 views.

**Comment by P0keDev** [comment]
Oh, I just noticed the github follower notification and was curious lol
